import { useState, useEffect, useMemo } from 'react';
import type { Okt, ExerciseStats } from '../types';
import { Icons } from '../components/ui/Icons';
import { HeartRateChart } from '../components/ui/Charts';
import {
    isStravaConnected,
    findOverlappingActivity,
    getActivityStreams,
    calculateDetailedStats
} from '../services/strava';

interface WorkoutDetailsViewProps {
    workout: Okt;
    onNavigate: (view: any) => void;
    onEdit: (workout: Okt) => void;
    onDelete: (id: string | number) => void;
    onUpdate: (workout: Okt) => void;

    allWorkouts: Okt[];
    onViewStats: (name: string) => void;
}

export function WorkoutDetailsView({ workout, onNavigate, onEdit, onDelete, onUpdate, allWorkouts, onViewStats }: WorkoutDetailsViewProps) {
    const [stravaConnected, setStravaConnected] = useState(false);
    const [stravaActivity, setStravaActivity] = useState<any | null>(null);
    const [exerciseStats, setExerciseStats] = useState<Record<string, ExerciseStats> | null>(null);
    const [setStats, setSetStats] = useState<Record<string, { avgHr: number, maxHr: number }> | null>(null);
    const [workoutStats, setWorkoutStats] = useState<{ calories: number, intensity: number, hrSeries?: number[] } | null>(null);
    const [isFetchingStrava, setIsFetchingStrava] = useState(false);
    const [showDeleteConfirm, setShowDeleteConfirm] = useState(false);

    useEffect(() => {
        isStravaConnected().then(setStravaConnected);
    }, []);

    useEffect(() => {
        // 1. Check for Cached Analysis AND Validity
        if (workout.stravaAnalysis) {
            // Validate that the cached keys actually match the current set IDs
            // (Fixes issue where IDs were regenerated by DB, breaking the map)
            const currentSetIds = new Set(workout.ovelser.flatMap(e => e.sett.map(s => String(s.id))));
            const cachedSetIds = Object.keys(workout.stravaAnalysis.setStats || {});

            const idsMatch = cachedSetIds.length === 0 || cachedSetIds.some(id => currentSetIds.has(id));
            const hasCalories = (workout.stravaAnalysis.workoutStats?.calories || 0) > 0;

            // INVALIDATE if IDs don't match OR if calories are 0 (to trigger new fallback calculation)
            const isCacheValid = idsMatch && hasCalories;

            if (isCacheValid) {
                console.log("Using cached Strava analysis");
                setExerciseStats(workout.stravaAnalysis.exerciseStats);
                setSetStats(workout.stravaAnalysis.setStats);
                setWorkoutStats(workout.stravaAnalysis.workoutStats);
                setStravaActivity({ id: workout.stravaAnalysis.activityId }); // Mock subset for UI link
                return;
            } else {
                console.warn("Cached Strava analysis has stale IDs. Re-fetching...");
            }
        }

        // 2. Fetch if connected and no cache
        // Only fetch if we have a valid start time and end time (or infer end time)
        // For now, if we don't have explicit end time, we can't find overlap accurately, 
        // but findOverlappingActivity handles fuzzy matching if needed or we assume workout length.
        // Ideally Okt should have endTime. If not, we use startTime + 2 hours window?
        // Let's assume valid start time.
        if (stravaConnected && workout.startTime) {
            const fetchStravaData = async () => {
                setIsFetchingStrava(true);
                try {
                    // If workout has no endTime, assume 90 mins for search window
                    const endTime = workout.endTime || new Date(new Date(workout.startTime!).getTime() + 90 * 60000).toISOString();

                    const activity = await findOverlappingActivity(workout.startTime!, endTime);

                    if (activity) {
                        setStravaActivity(activity);
                        const streams = await getActivityStreams(activity.id);
                        if (streams) {
                            // streams is already an object due to key_by_type=true
                            const stats = calculateDetailedStats(workout, activity, streams);
                            if (stats) {
                                setExerciseStats(stats.exerciseStats);
                                setSetStats(stats.setStats);
                                setWorkoutStats(stats.workoutStats);

                                // PERSIST CACHE
                                const updatedWorkout = {
                                    ...workout,
                                    stravaAnalysis: {
                                        activityId: activity.id,
                                        exerciseStats: stats.exerciseStats,
                                        setStats: stats.setStats,
                                        workoutStats: stats.workoutStats
                                    }
                                };
                                onUpdate(updatedWorkout);
                            }
                        }
                    }
                } catch (error) {
                    console.error("Failed to fetch Strava data", error);
                } finally {
                    setIsFetchingStrava(false);
                }
            };
            fetchStravaData();
        }
    }, [stravaConnected, workout]);

    // --- STATS CALCULATIONS ---
    const stats = useMemo(() => {
        // 1. DURATION
        let duration = "0m";
        if (workout.startTime && workout.endTime) {
            const diff = new Date(workout.endTime).getTime() - new Date(workout.startTime).getTime();
            const hrs = Math.floor(diff / 3600000);
            const mins = Math.floor((diff % 3600000) / 60000);
            duration = hrs > 0 ? `${hrs}t ${mins}m` : `${mins}m`;
        } else if (workout.ovelser.length > 0) {
            // Fallback: Estimates based on sets if no end time
            const sets = workout.ovelser.flatMap(e => e.sett).filter(s => s.completedAt);
            if (sets.length > 1) {
                sets.sort((a, b) => new Date(a.completedAt!).getTime() - new Date(b.completedAt!).getTime());
                const start = workout.startTime ? new Date(workout.startTime).getTime() : new Date(sets[0].completedAt!).getTime() - 60000;
                const end = new Date(sets[sets.length - 1].completedAt!).getTime();
                const diff = end - start;
                const hrs = Math.floor(diff / 3600000);
                const mins = Math.floor((diff % 3600000) / 60000);
                duration = hrs > 0 ? `${hrs}t ${mins}m` : `${mins}m`;
            }
        }

        // 2. TOTAL VOLUME
        let volume = 0;
        workout.ovelser.forEach(ex => {
            ex.sett.forEach(s => {
                if (s.completed) volume += (s.kg * s.reps);
            });
        });

        // 3. PRs
        const prExerciseIds = new Set<string | number>();
        const previousWorkouts = allWorkouts.filter(w => new Date(w.dato).getTime() < new Date(workout.dato).getTime());

        workout.ovelser.forEach(ex => {
            if (ex.type === 'Oppvarming' || ex.type === 'Egenvekt') return;

            // Max weight in THIS workout for this exercise
            const currentMax = Math.max(...ex.sett.map(s => s.kg));
            if (currentMax <= 0) return;

            // Find max weight in ALL previous workouts for same exercise name
            let historyMax = 0;
            previousWorkouts.forEach(pw => {
                const sameEx = pw.ovelser.find(pe => pe.navn === ex.navn); // Match by name!
                if (sameEx && sameEx.sett) {
                    const m = Math.max(...sameEx.sett.map(s => s.kg));
                    if (m > historyMax) historyMax = m;
                }
            });

            // If we beat history, it's a PR! 
            if (currentMax > historyMax) {
                prExerciseIds.add(ex.id);
            }
        });

        return { duration, volume, prCount: prExerciseIds.size, prExerciseIds };
    }, [workout, allWorkouts]);



    return (
        <div className="min-h-screen bg-slate-50 pb-40 relative">
            <header className="bg-white px-6 py-6 shadow-sm border-b border-slate-100 flex items-center gap-4 sticky top-0 z-50">
                <button
                    onClick={() => onNavigate('history')}
                    className="text-slate-400 p-3 hover:bg-slate-100 rounded-full transition-colors"
                >
                    <Icons.ChevronLeft className="w-8 h-8" />
                </button>
                <h1 className="text-2xl font-black text-slate-900 uppercase tracking-tighter italic">Øktdetaljer</h1>
            </header>

            <main className="max-w-xl mx-auto p-6 space-y-6 mt-2">
                <div className="bg-white p-8 rounded-[2.5rem] shadow-sm border border-slate-100 text-center">
                    <h2 className="text-3xl font-black text-slate-900 uppercase tracking-tighter italic mb-2">{workout.navn}</h2>
                    <p className="text-slate-400 font-bold uppercase tracking-widest text-xs">{workout.dato}</p>

                    {stravaConnected && (
                        <div className="mt-4 flex flex-col items-center">
                            {isFetchingStrava ? (
                                <div className="flex items-center gap-2 text-slate-400 font-bold text-xs uppercase tracking-wider animate-pulse">
                                    <div className="w-2 h-2 bg-slate-400 rounded-full animate-bounce" />
                                    Ser etter Strava-økt...
                                </div>
                            ) : stravaActivity ? (
                                <a
                                    href={`https://www.strava.com/activities/${stravaActivity.id}`}
                                    target="_blank"
                                    rel="noreferrer"
                                    className="flex items-center gap-2 text-[#FC4C02] font-black text-xs uppercase tracking-wider bg-[#FC4C02]/10 px-3 py-1 rounded-full hover:bg-[#FC4C02]/20 transition-colors"
                                >
                                    <Icons.Activity className="w-3 h-3" />
                                    Synkronisert med Strava
                                </a>
                            ) : (
                                <div className="flex items-center gap-2 text-slate-300 font-bold text-xs uppercase tracking-wider">
                                    <Icons.Activity className="w-3 h-3" />
                                    Ingen Strava-økt funnet
                                </div>
                            )}
                        </div>
                    )}
                </div>

                {/* STATS GRID */}
                <div className="grid grid-cols-3 gap-4 mb-4">
                    <div className="bg-white p-4 rounded-2xl shadow-sm border border-slate-100 flex flex-col items-center justify-center">
                        <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest text-center">Totalt Løft</p>
                        <p className="text-lg font-black text-slate-800 break-all">{stats.volume.toLocaleString()} KG</p>
                    </div>
                    <div className="bg-white p-4 rounded-2xl shadow-sm border border-slate-100 flex flex-col items-center justify-center">
                        <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest text-center">Tid</p>
                        <p className="text-lg font-black text-slate-800 whitespace-nowrap">{stats.duration}</p>
                    </div>
                    <div className="bg-white p-4 rounded-2xl shadow-sm border border-slate-100 flex flex-col items-center justify-center">
                        <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest text-center">Nye PRs</p>
                        <p className="text-lg font-black text-indigo-500">{stats.prCount} 🏆</p>
                    </div>
                </div>

                <div className="space-y-4">
                    {workout.ovelser.map((ex, i) => (
                        <div key={i} className="bg-white p-6 rounded-[2rem] shadow-sm border border-slate-100/50">
                            <div className="mb-4 pl-4 border-l-4 border-indigo-500">
                                <div className="flex justify-between items-center">
                                    <div className="flex items-center gap-3">
                                        <h3 className="font-black text-xl text-slate-800 uppercase tracking-tighter italic leading-none">{ex.navn}</h3>
                                        <button
                                            onClick={() => onViewStats(ex.navn)}
                                            className="p-1.5 bg-slate-100 hover:bg-slate-200 text-slate-600 rounded-lg transition-colors active:scale-95"
                                            title="Se statistikk"
                                        >
                                            <Icons.BarChart2 className="w-4 h-4" />
                                        </button>
                                    </div>
                                    {stats.prExerciseIds.has(ex.id) && (
                                        <span className="bg-yellow-100 text-yellow-700 text-[10px] font-black px-2 py-1 rounded-full border border-yellow-200 uppercase tracking-wide flex items-center gap-1">
                                            🏆 Ny PR
                                        </span>
                                    )}
                                </div>
                                {ex.type && ex.type !== 'Oppvarming' && (
                                    <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mt-1">{ex.type}</p>
                                )}
                            </div>
                            <div className="space-y-2">
                                {ex.sett.map((set, sIdx) => (
                                    <div key={sIdx} className="flex justify-between items-center px-4 py-2 bg-slate-50 rounded-xl">
                                        <span className="font-bold text-slate-400 text-xs uppercase tracking-wider">Sett {sIdx + 1}</span>

                                        {/* HR Stats Column if Strava connected (Placed LEFT of data now) */}


                                        {ex.type === 'Oppvarming' ? (
                                            <div className="flex gap-4 items-center flex-1 justify-end">
                                                <span className="font-black text-slate-700">
                                                    {(() => {
                                                        if (set.reps && set.reps > 0) {
                                                            const mins = Math.floor(set.reps / 60);
                                                            const secs = Math.floor(set.reps % 60);
                                                            return `${mins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
                                                        }
                                                        if (!set.startTime || !set.completedAt) return "00:00";
                                                        const diff = new Date(set.completedAt).getTime() - new Date(set.startTime).getTime();
                                                        if (diff < 0) return "00:00";
                                                        const mins = Math.floor(diff / 60000);
                                                        const secs = Math.floor((diff % 60000) / 1000);
                                                        return `${mins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
                                                    })()}
                                                    <span className="text-[10px] text-slate-400 font-bold ml-1">TID</span>
                                                </span>
                                            </div>
                                        ) : (
                                            <div className="flex gap-4 items-center flex-1 justify-end">
                                                <span className="font-black text-slate-700">{set.kg} <span className="text-[10px] text-slate-400 font-bold">KG</span></span>
                                                <span className="font-black text-slate-700">{set.reps} <span className="text-[10px] text-slate-400 font-bold">REPS</span></span>
                                            </div>
                                        )}

                                        {/* HR Stats Column if Strava connected (Placed RIGHT of data now) */}
                                        <div className="w-16 text-center ml-2">
                                            {setStats && setStats[set.id] ? (
                                                <span className="text-[10px] font-bold text-red-500 bg-red-50 px-2 py-1 rounded-md whitespace-nowrap">
                                                    ♥ {setStats[set.id].maxHr}
                                                </span>
                                            ) : (
                                                <span className="text-[10px] font-bold text-slate-300">-</span>
                                            )}
                                        </div>
                                    </div>
                                ))}
                            </div>

                            <div className="mt-4 pt-4 border-t border-slate-100 flex gap-3">

                                <span className="text-[10px] font-bold bg-red-50 text-red-500 px-2 py-1 rounded-md border border-red-100 uppercase tracking-wider flex items-center gap-1">
                                    <Icons.Activity className="w-3 h-3" /> Snitt: {(exerciseStats && exerciseStats[ex.id]) ? `${exerciseStats[ex.id].avgHr} bpm` : '-'}
                                </span>
                            </div>
                        </div>
                    ))}
                </div>

                {/* Workout Summary Stats */}
                <div className="bg-white p-6 rounded-[2rem] shadow-sm border border-slate-100">
                    <div className="flex justify-between items-center text-center divide-x divide-slate-100">
                        <div className="flex-1 px-4">
                            <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-1">Total Kalorier</p>
                            <p className="text-2xl font-black text-slate-800 italic">
                                {workoutStats ? `${workoutStats.calories} kcal` : '-'}
                            </p>
                        </div>
                        <div className="flex-1 px-4">
                            <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-1">Intensitet</p>
                            <div className="flex items-center justify-center gap-1">
                                {workoutStats ? (
                                    [...Array(5)].map((_, i) => (
                                        <div key={i} className={`w-3 h-8 rounded-full ${i < workoutStats.intensity ? 'bg-indigo-500' : 'bg-slate-100'}`} />
                                    ))
                                ) : (
                                    <span className="text-2xl font-black text-slate-200 italic">-</span>
                                )}
                            </div>
                            {workoutStats && <p className="text-xs font-bold text-slate-400 mt-1">{workoutStats.intensity}/5</p>}
                        </div>
                    </div>
                </div>

                {/* Heart Rate Chart */}
                {workoutStats?.hrSeries && workoutStats.hrSeries.length > 0 && (
                    <div className="bg-white p-6 rounded-[2rem] shadow-sm border border-slate-100 mt-4">
                        <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-4 text-center">Pulsutvikling</p>
                        <div className="h-32 w-full">
                            <HeartRateChart data={workoutStats.hrSeries} color="#ef4444" />
                        </div>
                    </div>
                )}

                <div className="flex gap-4 mt-8">
                    <button
                        onClick={() => onEdit(workout)}
                        className="flex-1 bg-slate-900 hover:bg-slate-800 text-white font-bold py-6 rounded-full shadow-xl shadow-slate-200 transition-all active:scale-95 flex items-center justify-center gap-3 text-lg uppercase tracking-wider"
                    >
                        <Icons.Pencil className="w-5 h-5" />
                        Rediger Økt
                    </button>

                    <button
                        onClick={() => setShowDeleteConfirm(true)}
                        className="w-20 bg-red-50 hover:bg-red-100 text-red-500 font-bold rounded-full transition-all active:scale-95 flex items-center justify-center border border-red-100"
                    >
                        <Icons.Trash2 className="w-6 h-6" />
                    </button>
                </div>
            </main>

            {/* Confirmation Modal */}
            {showDeleteConfirm && (
                <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-slate-900/50 backdrop-blur-sm animate-in fade-in duration-200">
                    <div className="bg-white rounded-[2rem] p-8 w-full max-w-sm shadow-2xl scale-100 animate-in zoom-in-95 duration-200">
                        <div className="flex flex-col items-center text-center space-y-4">
                            <div className="w-16 h-16 bg-red-50 rounded-full flex items-center justify-center mb-2">
                                <Icons.Trash2 className="w-8 h-8 text-red-500" />
                            </div>
                            <h3 className="text-2xl font-black text-slate-800 uppercase tracking-tighter italic">Slette treningsøkt?</h3>
                            <p className="text-slate-500 font-medium">
                                Er du sikker på at du vil slette <span className="text-slate-800 font-bold">{workout.navn}</span>?
                                <br />Denne handlingen kan ikke angres.
                            </p>

                            <div className="flex gap-3 w-full mt-4">
                                <button
                                    onClick={() => setShowDeleteConfirm(false)}
                                    className="flex-1 py-4 font-bold text-slate-600 bg-slate-100 hover:bg-slate-200 rounded-xl transition-colors uppercase tracking-wider text-sm"
                                >
                                    Avbryt
                                </button>
                                <button
                                    onClick={() => {
                                        onDelete(workout.id);
                                        setShowDeleteConfirm(false);
                                    }}
                                    className="flex-1 py-4 font-bold text-white bg-red-500 hover:bg-red-600 rounded-xl transition-colors uppercase tracking-wider text-sm shadow-lg shadow-red-200"
                                >
                                    Slett
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
}
