-- Create a table to store Strava tokens linked to Supabase users
create table if not exists user_integrations (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users(id) on delete cascade not null unique,
  provider text not null check (provider in ('strava')),
  access_token text not null,
  refresh_token text not null,
  expires_at bigint not null,
  athlete_data jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table user_integrations enable row level security;

-- Create Policies for user_integrations
drop policy if exists "Users can view own integrations" on user_integrations;
create policy "Users can view own integrations"
  on user_integrations for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own integrations" on user_integrations;
create policy "Users can insert own integrations"
  on user_integrations for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own integrations" on user_integrations;
create policy "Users can update own integrations"
  on user_integrations for update
  using (auth.uid() = user_id);

drop policy if exists "Users can delete own integrations" on user_integrations;
create policy "Users can delete own integrations"
  on user_integrations for delete
  using (auth.uid() = user_id);


-- FEEDBACK SYSTEM
create table if not exists feedback (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_email text not null,
  message text not null
);

alter table feedback enable row level security;

-- Create Policies for feedback
drop policy if exists "Authenticated users can insert feedback" on feedback;
create policy "Authenticated users can insert feedback"
  on feedback for insert
  to authenticated
  with check (true);

-- Allow only the admin to view feedback
-- Checks email in JWT token for security and performance
drop policy if exists "Admin can view feedback" on feedback;
create policy "Admin can view feedback"
  on feedback for select
  to authenticated
  using (
    (auth.jwt() ->> 'email') = 'stianberg2@gmail.com'
  );
